model = keras::keras_model_sequential()

model %>% 
  layer_reshape(input_shape = c(176400),
                target_shape = c(60, 60, 49)) %>%
  layer_conv_2d(filters = 100,
                        kernel_size = c(3,3),
                        name = "conv1",
                        activation = "relu") %>%
  layer_conv_2d(filters = 64,
                kernel_size = 1,
                name = "conv2_layer1",
                activation = "relu") %>%
  layer_conv_2d(filters = 64,
                kernel_size = 3,
                name = "conv2_layer2",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 1,
                name = "conv2_layer3",
                activation = "relu")%>%
  layer_conv_2d(filters = 64,
                kernel_size = 1,
                name = "conv2_layer4",
                activation = "relu") %>%
  layer_conv_2d(filters = 64,
                kernel_size = 3,
                name = "conv2_layer5",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 1,
                name = "conv2_layer6",
                activation = "relu")%>%
  layer_conv_2d(filters = 64,
                kernel_size = 1,
                name = "conv2_layer7",
                activation = "relu") %>%
  layer_conv_2d(filters = 64,
                kernel_size = 3,
                name = "conv2_layer8",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 1,
                name = "conv2_layer9",
                activation = "relu") %>%
  layer_conv_2d(filters = 128,
                kernel_size = 1,
                name = "conv3_layer1",
                activation = "relu") %>%
  layer_conv_2d(filters = 128,
                kernel_size = 3,
                name = "conv3_layer2",
                activation = "relu")%>%
  layer_conv_2d(filters = 512,
                kernel_size = 1,
                name = "conv3_layer3",
                activation = "relu")%>%
  layer_conv_2d(filters = 128,
                kernel_size = 1,
                name = "conv3_layer4",
                activation = "relu")%>%
  layer_conv_2d(filters = 128,
                kernel_size = 3,
                name = "conv3_layer5",
                activation = "relu")%>%
  layer_conv_2d(filters = 512,
                kernel_size = 1,
                name = "conv3_layer6",
                activation = "relu")%>%
  layer_conv_2d(filters = 128,
                kernel_size = 1,
                name = "conv3_layer7",
                activation = "relu")%>%
  layer_conv_2d(filters = 128,
                kernel_size = 3,
                name = "conv3_layer8",
                activation = "relu")%>%
  layer_conv_2d(filters = 512,
                kernel_size = 1,
                name = "conv3_layer9",
                activation = "relu")%>%
  layer_conv_2d(filters = 128,
                kernel_size = 1,
                name = "conv3_layer10",
                activation = "relu")%>%
  layer_conv_2d(filters = 128,
                kernel_size = 3,
                name = "conv3_layer11",
                activation = "relu")%>%
  layer_conv_2d(filters = 512,
                kernel_size = 1,
                name = "conv3_layer12",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 1,
                name = "conv4_layer1",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 3,
                name = "conv4_layer2",
                activation = "relu") %>%
  layer_conv_2d(filters = 1024,
                kernel_size = 1,
                name = "conv4_layer3",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 1,
                name = "conv4_layer4",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 3,
                name = "conv4_layer5",
                activation = "relu") %>%
  layer_conv_2d(filters = 1024,
                kernel_size = 1,
                name = "conv4_layer6",
                activation = "relu")%>%
  layer_conv_2d(filters = 256,
                kernel_size = 1,
                name = "conv4_layer7",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 3,
                name = "conv4_layer8",
                activation = "relu") %>%
  layer_conv_2d(filters = 1024,
                kernel_size = 1,
                name = "conv4_layer9",
                activation = "relu")%>%
  layer_conv_2d(filters = 256,
                kernel_size = 1,
                name = "conv4_layer10",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 3,
                name = "conv4_layer11",
                activation = "relu") %>%
  layer_conv_2d(filters = 1024,
                kernel_size = 1,
                name = "conv4_layer12",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 1,
                name = "conv4_layer13",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 3,
                name = "conv4_layer14",
                activation = "relu") %>%
  layer_conv_2d(filters = 1024,
                kernel_size = 1,
                name = "conv4_layer15",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 1,
                name = "conv4_layer16",
                activation = "relu") %>%
  layer_conv_2d(filters = 256,
                kernel_size = 3,
                name = "conv4_layer17",
                activation = "relu") %>%
  layer_conv_2d(filters = 1024,
                kernel_size = 1,
                name = "conv4_layer18",
                activation = "relu") %>%
  layer_conv_2d(filters = 512,
                kernel_size = 1,
                name = "conv5_layer1",
                activation = "relu") %>%
  layer_conv_2d(filters = 512,
                kernel_size = 3,
                name = "conv5_layer2",
                activation = "relu") %>%
  layer_conv_2d(filters = 2048,
                kernel_size = 1,
                name = "conv5_layer3",
                activation = "relu")  %>%
  layer_conv_2d(filters = 512,
                kernel_size = 1,
                name = "conv5_layer4",
                activation = "relu") %>%
  layer_conv_2d(filters = 512,
                kernel_size = 3,
                name = "conv5_layer5",
                activation = "relu") %>%
  layer_conv_2d(filters = 2048,
                kernel_size = 1,
                name = "conv5_layer6",
                activation = "relu")%>%
  layer_conv_2d(filters = 512,
                kernel_size = 1,
                name = "conv5_layer7",
                activation = "relu") %>%
  layer_conv_2d(filters = 512,
                kernel_size = 3,
                name = "conv5_layer8",
                activation = "relu") %>%
  layer_conv_2d(filters = 2048,
                kernel_size = 1,
                name = "conv5_layer9",
                activation = "relu") %>%
  layer_max_pooling_2d(pool_size = 2, strides = 2) %>%
  layer_dense(units = 1024,
              activation = "relu",
              name = "dens1")%>%
  layer_dense(units = 512,
              activation = "relu",
              name = "dens2")%>%
  layer_dense(units = 256,
              activation = "relu",
              name = "dens4")%>%
  layer_dense(units = 128,
              activation = "relu",
              name = "dens5")%>%
  layer_dense(units = 64,
              activation = "relu",
              name = "dens6")%>%
  layer_dense(units = 32,
              activation = "relu",
              name = "dens7")%>%
  layer_dense(units = 16,
              activation = "relu",
              name = "dens8")%>%
  layer_dense(units = 8,
              activation = "relu",
              name = "dens9")%>%
  layer_dense(units = 4,
              activation = "relu",
              name = "dens10")%>%
  layer_reshape(target_shape = 4) %>%
  layer_dense(units = 2,
              activation = "softmax",
              name = "output")

compile(model,loss="categorical_crossentropy",optimizer="adam",metrics="accuracy")



